# Generated by Django 3.2.4 on 2021-06-30 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='catalog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.catalog'),
        ),
    ]
